export const VNProvince = [
    "Hà Nội",
    "Hồ Chí Minh",
    "Đà Nẵng",
    "Hải Phòng",
    "Cần Thơ",
    "Hải Dương",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cao Bằng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Tĩnh",
    "Hải Dương",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái"
]

export const USProvince = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
]

export const TLProvince = [
    "Bangkok",
    "Samut Prakan",
    "Nonthaburi",
    "Pathum Thani",
    "Phra Nakhon Si Ayutthaya",
    "Ang Thong",
    "Lop Buri",
    "Sing Buri",
    "Chai Nat",
    "Saraburi",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Samut Sakhon",
    "Ratchaburi",
    "Samut Songkhram",
    "Phetchaburi",
    "Prachuap Khiri Khan",
    "Nakhon Ratchasima",
    "Buri Ram",
    "Surin",
    "Si Sa Ket",
    "Ubon Ratchathani",
    "Yasothon",
    "Chaiyaphum",
    "Amnat Charoen",
    "Bueng Kan",
    "Nong Bua Lamphu",
    "Khon Kaen",
    "Udon Thani",
    "Loei",
    "Nong Khai",
    "Maha Sarakham",
    "Roi Et",
    "Kalasin",
    "Sakon Nakhon",
    "Nakhon Phanom",
    "Mukdahan",
    "Chiang Mai",
    "Lamphun",
    "Lampang",
    "Uttaradit",
    "Phrae",
    "Nan",
    "Phayao",
    "Chiang Rai",
    "Mae Hong Son",
    "Nakhon Sawan",
    "Uthai Thani",
    "Kamphaeng Phet",
    "Tak",
    "Sukhothai",
    "Phitsanulok",
    "Phichit",
    "Phetchabun",
    "Ratchaburi",
    "Phetchaburi",
    "Nakhon Si Thammarat",
    "Krabi",
    "Phang Nga",
    "Phuket",
    "Surat Thani",
    "Ranong",
    "Chumphon",
    "Songkhla",
    "Satun",
    "Trang",
    "Phatthalung",
    "Pattani",
    "Yala",
    "Narathiwat",
    "Suphan Buri",
    "Kanchanaburi",
    "Phetchaburi",
    "Prachuap Khiri Khan",
    "Chumphon",
    "Ranong",
    "Surat Thani",
    "Phang Nga",
    "Phuket",
    "Krabi",
    "Nakhon Si Thammarat",
    "Trang",
    "Phatthalung",
    "Satun",
    "Songkhla",
    "Pattani",
    "Yala",
    "Narathiwat"
]