import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/common/header/header'
import Footer from '@/components/common/footer/footer'
import { Layout, Space } from 'antd';
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Space direction="vertical" style={{ width: '100%' }} size={[0, 48]}>
          <Layout style={{ minHeight: '100vh' }}>
            <Header/>
              <main className="flex min-h-screen flex-col items-center justify-between">
                {children}
              </main>
            <Footer/>
          </Layout>
        </Space>
      </body>
    </html>
  )
}
